# Generated by Django 4.1.5 on 2023-02-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0003_rename_slug_product_urlname'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='urlname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
