# Generated by Django 4.1.5 on 2023-02-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0004_category_urlname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='urlname',
            field=models.CharField(max_length=150),
        ),
    ]
