# Generated by Django 4.1.5 on 2023-02-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('laptop', 'laptop'), ('shoes', 'shoes')], max_length=255, null=True),
        ),
    ]
