# Generated by Django 4.1.5 on 2023-02-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('laptops', 'laptops'), ('shoes', 'shoes'), ('fashions', 'fashions'), ('mobiles', 'mobiles')], max_length=255),
        ),
    ]
