# Generated by Django 4.1.5 on 2023-02-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0010_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='urlname',
        ),
    ]
