# Generated by Django 4.1.5 on 2023-02-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0012_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
