# Generated by Django 4.1.5 on 2023-02-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0013_cart_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
